// <auto-generated />
using System;
using Ajeer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ajeer.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223182416_NotificatonRelatedId")]
    partial class NotificatonRelatedId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ajeer.Api.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UploaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceAreaId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.BookingServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServiceItems", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.ProviderService", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("ServiceProviderId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ProviderServices", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.ProviderServiceArea", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceAreaId")
                        .HasColumnType("int");

                    b.HasKey("ServiceProviderId", "ServiceAreaId");

                    b.HasIndex("ServiceAreaId");

                    b.ToTable("ProviderServiceAreas", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BasePrice = 10m,
                            CategoryId = -1,
                            EstimatedHours = 1.5m,
                            Name = "Leak Repair"
                        },
                        new
                        {
                            Id = -2,
                            BasePrice = 25m,
                            CategoryId = -1,
                            EstimatedHours = 3m,
                            Name = "Pipe Installation"
                        },
                        new
                        {
                            Id = -3,
                            BasePrice = 15m,
                            CategoryId = -1,
                            EstimatedHours = 2m,
                            Name = "Drain Cleaning"
                        },
                        new
                        {
                            Id = -4,
                            BasePrice = 10m,
                            CategoryId = -2,
                            EstimatedHours = 1m,
                            Name = "Light Fixture Installation"
                        },
                        new
                        {
                            Id = -5,
                            BasePrice = 30m,
                            CategoryId = -2,
                            EstimatedHours = 2.5m,
                            Name = "Wiring Maintenance"
                        },
                        new
                        {
                            Id = -6,
                            BasePrice = 40m,
                            CategoryId = -3,
                            EstimatedHours = 4m,
                            Name = "Home Deep Cleaning"
                        },
                        new
                        {
                            Id = -7,
                            BasePrice = 30m,
                            CategoryId = -3,
                            EstimatedHours = 3m,
                            Name = "Office Cleaning"
                        },
                        new
                        {
                            Id = -8,
                            BasePrice = 20m,
                            CategoryId = -3,
                            EstimatedHours = 2m,
                            Name = "Carpet Cleaning"
                        },
                        new
                        {
                            Id = -9,
                            BasePrice = 60m,
                            CategoryId = -4,
                            EstimatedHours = 6m,
                            Name = "Interior Painting"
                        },
                        new
                        {
                            Id = -10,
                            BasePrice = 80m,
                            CategoryId = -4,
                            EstimatedHours = 8m,
                            Name = "Exterior Painting"
                        },
                        new
                        {
                            Id = -11,
                            BasePrice = 30m,
                            CategoryId = -5,
                            EstimatedHours = 3m,
                            Name = "Door Installation"
                        },
                        new
                        {
                            Id = -12,
                            BasePrice = 20m,
                            CategoryId = -5,
                            EstimatedHours = 2m,
                            Name = "Furniture Repair"
                        },
                        new
                        {
                            Id = -13,
                            BasePrice = 20m,
                            CategoryId = -6,
                            EstimatedHours = 2m,
                            Name = "AC Repair"
                        },
                        new
                        {
                            Id = -14,
                            BasePrice = 15m,
                            CategoryId = -6,
                            EstimatedHours = 1.5m,
                            Name = "Fridge Maintenance"
                        },
                        new
                        {
                            Id = -15,
                            BasePrice = 20m,
                            CategoryId = -6,
                            EstimatedHours = 2m,
                            Name = "Washing Machine Repair"
                        },
                        new
                        {
                            Id = -16,
                            BasePrice = 20m,
                            CategoryId = -7,
                            EstimatedHours = 2m,
                            Name = "Grass Cutting"
                        },
                        new
                        {
                            Id = -17,
                            BasePrice = 50m,
                            CategoryId = -7,
                            EstimatedHours = 5m,
                            Name = "Garden Design"
                        },
                        new
                        {
                            Id = -18,
                            BasePrice = 15m,
                            CategoryId = -8,
                            EstimatedHours = 1.5m,
                            Name = "Laptop Repair"
                        },
                        new
                        {
                            Id = -19,
                            BasePrice = 30m,
                            CategoryId = -8,
                            EstimatedHours = 3m,
                            Name = "Network Setup"
                        },
                        new
                        {
                            Id = -20,
                            BasePrice = 10m,
                            CategoryId = -8,
                            EstimatedHours = 1m,
                            Name = "Software Installation"
                        },
                        new
                        {
                            Id = -21,
                            BasePrice = 80m,
                            CategoryId = -9,
                            EstimatedHours = 8m,
                            Name = "Home Moving"
                        },
                        new
                        {
                            Id = -22,
                            BasePrice = 100m,
                            CategoryId = -9,
                            EstimatedHours = 10m,
                            Name = "Office Relocation"
                        },
                        new
                        {
                            Id = -23,
                            BasePrice = 30m,
                            CategoryId = -9,
                            EstimatedHours = 2m,
                            Name = "Furniture Delivery"
                        });
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceAreas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AreaName = "Abdoun",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -2,
                            AreaName = "Jabal Al-Weibdeh",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -3,
                            AreaName = "Shmeisani",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -4,
                            AreaName = "Al-Rabieh",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -5,
                            AreaName = "Dabouq",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -6,
                            AreaName = "Al-Jubeiha",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -7,
                            AreaName = "Al-Bayader",
                            CityName = "Amman"
                        },
                        new
                        {
                            Id = -8,
                            AreaName = "Tla' Al-Ali",
                            CityName = "Amman"
                        });
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Leak repair, pipe installation, and maintenance.",
                            IconUrl = "plumbing.png",
                            Name = "Plumbing"
                        },
                        new
                        {
                            Id = -2,
                            Description = "Electrical repairs, wiring, and installations.",
                            IconUrl = "electrical.png",
                            Name = "Electrical"
                        },
                        new
                        {
                            Id = -3,
                            Description = "Home, office, and carpet cleaning.",
                            IconUrl = "cleaning.png",
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = -4,
                            Description = "Interior and exterior wall painting.",
                            IconUrl = "painting.png",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = -5,
                            Description = "Wood furniture and door repair or installation.",
                            IconUrl = "carpentry.png",
                            Name = "Carpentry"
                        },
                        new
                        {
                            Id = -6,
                            Description = "Fixing washing machines, fridges, and ACs.",
                            IconUrl = "appliance_repair.png",
                            Name = "Appliance Repair"
                        },
                        new
                        {
                            Id = -7,
                            Description = "Lawn care, trimming, and garden design.",
                            IconUrl = "gardening.png",
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = -8,
                            Description = "Computer setup, repair, and software help.",
                            IconUrl = "it_support.png",
                            Name = "IT Support"
                        },
                        new
                        {
                            Id = -9,
                            Description = "Home and office moving or furniture delivery.",
                            IconUrl = "moving_and_delivery.png",
                            Name = "Moving & Delivery"
                        });
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceProvider", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdCardAttachmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId");

                    b.HasIndex("IdCardAttachmentId")
                        .IsUnique()
                        .HasFilter("[IdCardAttachmentId] IS NOT NULL");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DurationInDays = 30,
                            Name = "1 Month Plan",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = -2,
                            DurationInDays = 90,
                            Name = "3 Month Plan",
                            Price = 50.00m
                        });
                });

            modelBuilder.Entity("Ajeer.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ajeer.Api.Models.Attachment", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Booking", "Booking")
                        .WithMany("Attachments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ajeer.Api.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Booking", b =>
                {
                    b.HasOne("Ajeer.Api.Models.ServiceArea", "ServiceArea")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceArea");

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajeer.Api.Models.BookingServiceItem", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Booking", "Booking")
                        .WithMany("BookingServiceItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Message", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Booking", "Booking")
                        .WithMany("Messages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Notification", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ajeer.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ProviderService", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ProviderServiceArea", b =>
                {
                    b.HasOne("Ajeer.Api.Models.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("ProviderServiceAreas")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceArea");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Review", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("Ajeer.Api.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Schedule", b =>
                {
                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Service", b =>
                {
                    b.HasOne("Ajeer.Api.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceProvider", b =>
                {
                    b.HasOne("Ajeer.Api.Models.Attachment", "IdCardAttachment")
                        .WithOne()
                        .HasForeignKey("Ajeer.Api.Models.ServiceProvider", "IdCardAttachmentId");

                    b.HasOne("Ajeer.Api.Models.User", "User")
                        .WithOne("ServiceProvider")
                        .HasForeignKey("Ajeer.Api.Models.ServiceProvider", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCardAttachment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Subscription", b =>
                {
                    b.HasOne("Ajeer.Api.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajeer.Api.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ajeer.Api.Models.Booking", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BookingServiceItems");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceArea", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Ajeer.Api.Models.ServiceProvider", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ProviderServiceAreas");

                    b.Navigation("ProviderServices");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Ajeer.Api.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessages");

                    b.Navigation("ServiceProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
